ecomerce/ecomerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    # path("stk/", include("payment.urls")),
    path('register', user_views.register, name='register'),
    path('login',user_views.login_request,name='login'),
    path('logout/',user_views.logout_request,name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomerce/store/urls.py
from django.urls import path
from .import views

app_name = "Store"

urlpatterns=[
    path('',views.store,name='home'),
    path('cart/',views.cart,name='cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('update_item/',views.updateItem,name='update_item'),
    path('process_order/',views.processOrder,name='process_order'),
    path('search/',views.search,name='search'),
    path("category/<str:name>", views.category, name="category"),
]

ecomerce/store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE, null=True,blank=True)
    name = models.CharField(max_length= 200,null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=200)
    # class Meta:
    #     ordering = ['name']
    #     indexes = [
    #     models.Index(fields=['name']),
    #     ]
    #     verbose_name = 'category'
    #     verbose_name_plural = 'categories'
    def __str__(self):
        return self.name
 
class Product(models.Model):
    name = models.CharField(max_length=200,null=True)
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False,null=True, blank=False)
    image = models.ImageField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
class Order(models.Model):
    customer = models.ForeignKey(Customer,on_delete= models.SET_NULL,null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False,null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitem_set.all()
        for i in orderitems:
            if i.product.digital == False:
                shipping = True
        return shipping
    
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    
    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total
    
class OrderItem(models.Model):
    product = models.ForeignKey(Product,on_delete= models.SET_NULL,null=True, blank=True)
    order = models.ForeignKey(Order,on_delete= models.SET_NULL,null=True, blank=True)
    quantity = models.IntegerField(default=0,null=True,blank=False)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total    
class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete= models.SET_NULL,null=True, blank=True)
    order = models.ForeignKey(Order,on_delete= models.SET_NULL,null=True, blank=True)
    address = models.CharField(max_length=200,null=True)
    city = models.CharField(max_length=200,null=True)
    state = models.CharField(max_length=200,null=True)
    zipcode = models.CharField(max_length=200,null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecomerce/store/views.py
from django.shortcuts import render,redirect
from django.http import JsonResponse, HttpResponse
import json
import datetime
from django.contrib import messages

from .models import *
from . utils import cookieCart,cartData,guestOrder
from django_daraja.mpesa.core import MpesaClient
# Create your views here.
def store(request):
    data = cartData(request)
    cartItems = data['cartItems']

    products = Product.objects.all()
    category = Category.objects.all()

    for cat in category:
        cat_products = Product.objects.filter(category=cat)
        
    context= {'products':products,'cartItems': cartItems,'cat_products':cat_products, 'categories':category}
    return render(request,'store/store.html',context)
   

def category(request, name):
    data = cartData(request)
    cartItems = data['cartItems']
    # Grab the category from the url
    try:
        category = Category.objects.get(name=name)
        cat_products = Product.objects.filter(category=category)
        return  render(request, "store/category.html", {'cat_products':cat_products, 'category':category,'cartItems':cartItems})

    except:
        messages.warning(request, "That category doesn't exist")
        return render(request,"store/category.html")

def cart(request):
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context= {'items':items, 'order':order,'cartItems':cartItems}
    return render(request,'store/cart.html',context)

def checkout(request): 
    data = cartData(request)
    cartItems = data['cartItems']
    order = data['order']
    items = data['items']

    context= {'items':items, 'order':order,'cartItems':cartItems,'shipping':False}
    return render(request,'store/checkout.html',context)

def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('productId:',productId)
    print('Action:',action)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer,complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order,product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item was added', safe=False)

def processOrder(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer,complete=False)

    else:
        customer, order = guestOrder(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()
    if order.shipping ==True:
        ShippingAddress.objects.create(
            order = order,
            customer = customer,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            state = data['shipping']['state'],
            zipcode = data['shipping']['zipcode'],
        )

    return JsonResponse("Payment complete",safe=False)

def search(request):
    data = cartData(request)
    cartItems = data['cartItems']
    if request.method == 'GET':
        query = request.GET.get('query')

        if query:
            prod = Product.objects.filter(name__icontains=query)
            return render(request, "store/search.html", {'prod':prod,'cartItems':cartItems})

ecomerce/templates/store/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sunfresh</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
<body>
     
      <!-- nav/menu -->
	    <nav class="navbar">
            <a href="#" class="logo">
                <img src="{% static 'images/logo.png' %}" alt="Sunfresh Logo">
            </a>
            <!-- <img class="logo" id="logo" src="{% static 'images/logo.png' %}" alt="Sunfresh Logo"> -->
            <input class="menu-btn" type="checkbox" id="menu-btn" />
            <label class="menu-icon" for="menu-btn"><span class="nav-icon"></span></label>
            <!-- Menu-->
            <ul class="menu">
                <li><a href="">Home</a></li>
                <li><a href="">About us</a></li>
                <li><a href="">Contact</a></li>
                {% if user.is_authenticated %}
            <li><a href="logout">Logout</a></li>
            {% else %}
            <li><a class="nav-item nav-link" href="{%url 'login'%}">Login</a></li>
            <li><a class="nav-item nav-link" href="{%url 'register'%}">Register</a></li>
            {% endif %}
            </ul>
        </nav>
	    <!-- end of nav/menu -->
    
    
<!-- header section ends here -->

    {% block content %}{% endblock %}
    <!-- footer section starts here -->

    <section class="footer ">
        <div class="share ">
            <a href="https://web.facebook.com/kelvin.sanga.7334?_rdc=1&_rdr " class="fab fa-facebook-f " aria-hidden="true "></a>
            <a href="https://twitter.com/home " class="fab fa-twitter " aria-hidden="true "></a>
            <a href="https://www.instagram.com/ " class="fab fa-instagram " aria-hidden="true "></a>
            <a href="https://ke.linkedin.com/ " class="fab fa-linkedin " aria-hidden="true "></a>
            <a href="https://github.com/Sanga78 " class="fab fa-github " aria-hidden="true "></a>
        </div>

        <div class="links ">
            <a href="# ">home</a>
            <a href="# ">about</a>
            <a href="# ">menu</a>
            <a href="#products ">products</a>
            <a href="# ">review</a>
            <a href="# ">contact</a>
            <a href="# ">blogs</a>
        </div>
        <div class="credit ">created by <span>mr. kelvin kipkosgei</span> | all rights reserved</div>
    </section>
    <!-- footer section ends here -->

</body>
</html>

ecomerce/templates/store/cart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'Store:home' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> Ksh {{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'Store:checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>ksh {{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>ksh {{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}

ecomerce/templates/store/checkout.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
				<button id="make-payment">Make Payment</button>
			</div>
			
		</div>

	    <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'Store:cart' %}">&#x2190; Back to cart</a>
                <hr>
                <h3>Order Summary</h3>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
                    <div style="flex:2"><p>{{item.product.name}}</p></div>
                    <div style="flex:1"><p>ksh {{item.product.price}}</p></div>
                    <div style="flex:1"><p>{{item.quantity}}</p></div>
                </div>
                {% endfor %}
                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: ksh {{order.get_cart_total|floatformat:2}}</h5>
            </div>      
    
        </div>
	</div>
	<script type="text/javascript">
		var shipping = '{{order.shipping}}'
		var total = '{{order.get_cart_total}}'
		if (shipping == 'False'){
			document.getElementById('shipping-info').innerHTML = ''
		}
		var form = document.getElementById('form')

		if(user != 'AnonymousUser'){
			document.getElementById('user-info').innerHTML = ''
		}
		
		if(shipping == 'False' && user != 'AnonymousUser'){
			document.getElementById('form-wrapper').classList.add("hidden")
			document.getElementById('payment-info').classList.remove("hidden")
		}

		form.addEventListener('submit', function(e){
			e.preventDefault()
			console.log("Form submited...")
			document.getElementById('form-button').classList.add('hidden')
			document.getElementById('payment-info').classList.remove('hidden')
		})	

		document.getElementById('make-payment').addEventListener('click',function(e){
			submitFormData()
		})

		function submitFormData(){
			console.log("Payment button clicked")

			var userFormData = {
				'name':null,
				'email':null,
				'total':total,
			}
			var shippingInfo = {
				'address':null,
				'city':null,
				'state':null,
				'zipcode':null,
			}

			if(shipping != 'False'){
				shippingInfo.address = form.address.value
				shippingInfo.city = form.city.value
				shippingInfo.state = form.state.value
				shippingInfo.zipcode = form.zipcode.value
			}

			if(user == 'AnonymousUser'){
				userFormData.name = form.name.value
				userFormData.email = form.email.value
			}

			var url = '/process_order/'
			fetch(url,{
				method:'POST',
				headers:{
					'Content-Type':'application/json',
					'X-CSRFToken': csrftoken,
				},
				body:JSON.stringify({'form':userFormData,'shipping':shippingInfo})
			})
			.then((response) => response.json())
			.then((data) => {
				console.log('Success:', data);
				alert('Proceed to pay');
				cart = {}
				document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                window.location.href = "{% url 'Store:home' %}";
			})			
		}
	</script>
{% endblock content %}

ecomerce/templates/store/main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Ecom</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript">
		var user = '{{request.user}}'

		function getToken(name){
			var cookieValue = null;
			if (document.cookie && document.cookie !== ''){
				var cookies = document.cookie.split(';');
				for (var i = 0; i < cookies.length; i++) {
					var cookie = cookies[i].trim();
					// does the cookie begin with the name we want
					if (cookie.substring(0, name.length + 1) === (name + '=')){
						cookieValue = decodeURIComponent(cookie.substring(
							name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}
		var csrftoken = getToken('csrftoken');

		function getCookie(name){
			//split cookie string and get all individual name=value pairs is an array
			var cookieArr = document.cookie.split(";");

			//loop through the array elements
			for (var i = 0; i < cookieArr.length; i++){
				var cookiePair = cookieArr[i].split("=");

				/*removing whitespace at the beginning of the cookie name
				and compare it with the string */
				if(name == cookiePair[0].trim()){
					//Decode the cookie value and return
					return decodeURIComponent(cookiePair[1]);
				}
			}
			//Return null if not found
			return null;
		}

		var cart = JSON.parse(getCookie('cart'))
		if(cart == undefined){
			cart = {}
			console.log("Cart was created!")
			document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
		}
		console.log('Cart:', cart)
	</script>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'Store:home' %}">EcoMart</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="{% url 'Store:home' %}">Store <span class="sr-only">(current)</span></a>
	      </li>
	 
	    </ul>
		<div class="nav-item dropdown">
			<a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Categories</a>
			<div class="dropdown-menu m-0">

				<li class="nav-item {% if navbar == 'category' %}active {% endif %}">
					<a href="{% url 'Store:category' 'Juices' %}" class="nav-item nav-link active dropdown-item">Juices</a>
				</li>

				<li class="nav-item {% if navbar == 'category' %}active {% endif %}">
					<a href="{% url 'Store:category' 'Fruit' %}" class="nav-item nav-link active dropdown-item">Fruits</a>
				</li>

				<li class="nav-item {% if navbar == 'category' %}active {% endif %}">
					<a href="{% url 'Store:category' 'Drinks' %}" class="nav-item nav-link active dropdown-item">Soft Drinks</a>
				</li>
			</div>
		</div>
	    <div class="form-inline my-2 my-lg-0">
			{% if user.is_authenticated %}
	     	<a href="{% url 'logout' %}"class="btn btn-warning">Logout</a>
			{% else %}
			<a href="{% url 'login' %}"class="btn btn-warning">Login</a>
			{% endif %}
	     	<a href="{% url 'Store:cart' %}">
	    		<img  id="cart-icon" src="{% static 'images/cart.png' %}">
	    	</a>
	    	<p id="cart-total">{{cartItems}}</p>
			<div class="search-form">
				<form class="d-flex" role="search" method="get" action="{% url 'Store:search' %}" >
					<input class="form-control me-2" name="query" type="search" placeholder="Search hear..." aria-label="Search">
				</form>
			</div>
			
			
	    </div>
	  </div>
	</nav>

     <div class="container">
            <br>
            {% block content %}


            {% endblock content %}
         </div>


	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<script src="{% static 'js/cart.js' %}"></script>
</body>
</html>

ecomerce/templates/store/store.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		{% for product in products %}
		<div class="col-lg-4">
			<img class="thumbnail" src="{{product.imageURL}}">
			<div class="box-element product">
				<h6><strong>{{product.name}}</strong></h6>
				<hr>

				<button data-product="{{product.id}}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to Cart</button>
				<a class="btn btn-outline-success" href="#">View</a>
				<h4 style="display: inline-block; float: right"><strong>ksh{{product.price|floatformat:2}}</strong></h4>

			</div>
		</div>
		{% endfor %}
    </div>

{% endblock content %}